version: '3.8'

services:
  mysql:
    image: mysql:8.3.0
    container_name: order-service-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data:
